FROM mysql:latest
MAINTAINER Abhishek Garg 

ENV MYSQL_ROOT_PASSWORD=${{ secrets.SECRETS_PASSWORDS }}
ENV MYSQL_DATABASE=Admin
ENV MYSQL_USER=test
ENV MYSQL_PASSWORD=${{ secrets.SECRETS_PASSWORDS }}

EXPOSE 3306 
