FROM mysql:latest
MAINTAINER Abhishek Garg 

ENV MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
ENV MYSQL_DATABASE=Admin
ENV MYSQL_USER=test
ENV MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}

EXPOSE 3306 
