name: Continous Integration 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

  services: 
  mysql:
  image: mysql:latest
  ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: newdb
      MYSQL_USER: adminuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: admin
 steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker-compose up -d 
