name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build WordPress Docker image
    
      run:

         docker buildx build --platform linux/amd64,linux/arm64 -t mywordpress:latest -f Dockerfile.wordpress .
          
    - name: Build MySQL Docker image

      run: 

           docker buildx build --platform linux/amd64,linux/arm64 -t mydockerhubusername/mywordpress:latest -f Dockerfile.mysql .        
    

          
