name: Building Docker Images for Wordpress and MYSQL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build WordPress Docker image
    
      run:

         docker buildx build -t mywordpress:latest -f wordpress.Dockerfile .
          
    - name: Build MySQL Docker image

      run: 

           docker buildx build  -t mymysql:latest -f mysql.Dockerfile .        
    

          
